# Generated by Django 4.2.30 on 2026-05-11 07:17

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('percent', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(100)])),
                ('pay_date', models.DateTimeField(db_index=True)),
                ('payer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='clients.client')),
            ],
            options={
                'db_table': 'payments',
                'indexes': [models.Index(fields=['payer', 'pay_date'], name='payment_payer_date_idx')],
            },
        ),
    ]
